---
title: "Plotter_R"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

# Read in libraries and data frame

library(tidyverse)
library(maps)
library(RColorBrewer)

df <- read.csv("../../usa/ar/clustered.csv")

```

```{r}

# Create plots of both the state counties and the equal kmeans clustering

no_axes <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank()
)

states_df <- map_data("state")
county_df <- map_data("county")
states_sub <- states_df %>% filter(region=="arkansas")
county_sub <- subset(county_df, region == "arkansas")

plotState <- ggplot() + 
  geom_polygon(data=states_sub, 
               aes(x = long, y = lat, group = group), 
               fill="grey", color="black") + 
  geom_polygon(data=county_sub, 
               aes(x = long, y = lat, group = group), 
               fill = NA, color = "white") +
  geom_polygon(color = "black", fill = NA) + 
  coord_fixed(1.3) +
  guides(fill = FALSE) + 
  theme_classic() +
  no_axes + 
  xlab("Latitude") + 
  ylab("Longitude") + 
  labs(title="Arkansas")

plotKMeans <- ggplot() + 
  geom_point(data=df, aes(x=lon, y=lat, color=label)) +
  coord_fixed(1.3) + 
  geom_polygon(data=states_sub, 
               aes(x = long, y = lat, group = group), 
               fill=NA, color="black") + 
  geom_polygon(data=county_sub, 
               aes(x = long, y = lat, group = group), 
               fill = NA, color = "white") + 
  geom_polygon(color = "black", fill = NA) + 
  guides(fill = FALSE) + 
  theme_classic() +
  no_axes + 
  xlab("Latitude") + 
  ylab("Longitude") + 
  labs(title="Arkansas")

```

```{r}

# Save plot as a .png

ggsave("../../img/ar_clustered.png", plot=plotKMeans)
          
```